name: reboot_app_3
description: the next generatiion of reboot app

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 4.3.0

environment:
  sdk: ">=2.10.5 <3.0.0"

dependencies:
  chips_choice: ^3.0.0
  cloud_firestore: ^4.3.1
  cupertino_icons: ^1.0.5
  equatable: ^2.0.3
  firebase_analytics: ^10.1.0
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  firebase_crashlytics: ^3.0.10
  firebase_messaging: ^14.2.1
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-alpha.6
  flutter_local_notifications: 13.0.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.2
  flutter_rounded_date_picker: ^3.0.1
  get_it: ^7.2.0
  google_sign_in: ^6.0.2
  http: ^0.13.4
  iconsax: ^0.0.8
  in_app_review: ^2.0.6
  intl: ^0.17.0
  local_auth: ^2.1.2
  path: null
  promize_sdk: ^0.2.3
  provider: ^6.0.2
  rxdart: null
  shared_preferences: ^2.0.15
  sign_in_with_apple: ^4.0.0
  syncfusion_flutter_calendar: ^21.1.38
  the_apple_sign_in: ^1.1.1
  url_launcher: ^6.1.3

dev_dependencies:
  dart_code_metrics: ^5.4.0
  flutter_launcher_icons: ^0.13.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  image_path: "asset/illustrations/app-icon.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - asset/illustrations/app-icon.png
    - asset/illustrations/app-logo.png
    - asset/i18n/en.json
    - asset/i18n/ar.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: DINNextLTArabic
      fonts:
        - asset: fonts/DINNextLTArabic-Bold.ttf
          weight: 700
        - asset: fonts/DINNextLTArabic-UltraLight.ttf
          weight: 300
        - asset: fonts/DINNextLTArabic-Light.ttf
          weight: 400
        - asset: fonts/DINNextLTArabic-Medium.ttf
          weight: 600
        - asset: fonts/DINNextLTArabic-Regular.ttf
          weight: 500
    - family: IBMArabic
      fonts:
        - asset: fonts/IBMPlexSansArabic-Thin.ttf
          weight: 100
        - asset: fonts/IBMPlexSansArabic-ExtraLight.ttf
          weight: 200
        - asset: fonts/IBMPlexSansArabic-Light.ttf
          weight: 300
        - asset: fonts/IBMPlexSansArabic-Regular.ttf
          weight: 400
        - asset: fonts/IBMPlexSansArabic-Medium.ttf
          weight: 500
        - asset: fonts/IBMPlexSansArabic-SemiBold.ttf
          weight: 600
        - asset: fonts/IBMPlexSansArabic-Bold.ttf
          weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
